apiVersion: v1
kind: ServiceAccount
metadata:
  name: sa
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        # https://github.com/nginxinc/docker-nginx-unprivileged
      - name: frontend
        image: localhost:5000/react-test-frontend:0.1
        imagePullPolicy: Always
        volumeMounts:
            - mountPath: /etc/nginx
              readOnly: true
              name: nginx-conf
            - mountPath: /tmp/nginx
              name: tmpnginx
              readOnly: false
        resources:
          limits:
            memory: "64Mi"
            cpu: "128m"
          requests:
            memory: "64Mi"
            cpu: "128m"
        ports:
        - containerPort: 8080
        env:
        - name: REACT_APP_BASE_URL
          valueFrom:
            configMapKeyRef:
              name: frontend-nginx-conf
              key: REACT_APP_BASE_URL
      volumes:
        - name: nginx-conf
          configMap:
            name: frontend-nginx-conf
            items:
              - key: nginx.conf
                path: nginx.conf
              - key: mime.types
                path: mime.types
        - name: tmpnginx
          emptyDir: {}
      serviceAccountName: sa


---

apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  type: ClusterIP
  selector:
    app: frontend
  ports:
    - port: 80
      targetPort: 8080
